### ISSUE TITLE
From<T> trait breaks dependencies

### ISSUE THREAD

**Issue by rachitnigam** [cfallin/boolean_expression#16]
Looks like commit 010521576987a028ed3a952fa505b1781ac391cc introduced a general from implementation that overlaps with any `T` that implements certain traits. This will break code that tries to provide its own implementation of `From<T>` (example attached).

https://github.com/cucapra/futil/blob/80aed57976ddac86a99c54dc546d42be16f073cc/calyx/src/passes/simplify_guards.rs#L10-L20

AFAIK, rust's trait system doesn't allow for multiple conflicting implementations so the upstream crate has to hide the implementation/not provide it.

On a side note, thanks for implementing this crate and open sourcing it!

**Comment by cfallin** [comment]
Sorry about that! I hadn't fully thought through the implications of providing the `From` impl there. I agree that allowing flexibility is the right policy, so it's better to allow custom `From` impls.

I went ahead and removed this and published version 0.4.3, then yanked 0.4.2 since it was an inadvertent API-break.

@arlyon sorry about this -- hopefully adding the simple `From` impl on the user side won't be too much inconvenience in your use-case!

**Comment by arlyon** [comment]
No worries, in retrospect it is clearly a restriction not a convenience so I agree.
